czasDoOdliczeniaStartuGry: 30
dlugoscTrwaniaWarmupu: 30
dlugoscTrwaniaDeathMatchu: 30
dlugoscTrwaniaAfterMatchu: 30
minimalnaLiczbaGraczyDoStartuGry: 2
minimalnaLiczbaGraczyDoUtrzymaniaOdliczaniaStartuGry: 2
