czasDoOdliczeniaStartuGry: 30
dlugoscTrwaniaWarmupu: 30
dlugoscTrwaniaDeathMatchu: 30
dlugoscTrwaniaAfterMatchu: 30
minimalnaLiczbaGraczyDoStartuGry: 2
minimalnaLiczbaGraczyDoUtrzymaniaOdliczaniaStartuGry: 2
lobby:
  spawn: 'world,0,73,0,0,0'
druzyny:
  druzyna1:
    spawn: 'world,0,0,0,0,0'
  druzyna2:
    spawn: 'world,0,0,0,0,0'