name: MyFirstPlugin
version: 1.0
main: com.gmail.grzegorz2047.myfirstplugin.PluginStarter
commands:
  spawns:
    description: Komenda zapisujaca spawn druzyn
    usage: /spawn args
    aliases: [spns, sp]
  bans:
    description: Komenda banujaca gracza
    usage: /bans args
    aliases: [bns, bs]